import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'

import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='layout'>
          <Sidebar />
          {children}
          <Toaster position='top-right'/>
        </div>
      </body>
    </html>
  )
}
